"""add color to boards

Revision ID: 68c201a6c8aa
Revises: 79facad17c20
Create Date: 2026-10-08 19:31:47.991190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c201a6c8aa'
down_revision: Union[str, Sequence[str], None] = '79facad17c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('color', sa.String(length=20), server_default='gray', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'color')
    # ### end Alembic commands ###
